<a href="https://colab.research.google.com/github/2303a51295madhuri/python-for-data-science/blob/main/LAB_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Perform basic arithmetic operations like addition and subtraction
on 2D NumPy arrays representing matrices

In [ ]:
import numpy as np
A=np.array([[20,30,40],[40,50,60]])
B=np.array([[15,10,25],[20,25,35]])
print(A)
print(B)


[[20 30 40]
 [40 50 60]]
[[15 10 25]
 [20 25 35]]


In [ ]:
addition=np.add(A,B)
print(addition)
subtraction=np.subtract(A,B)
print(subtraction)

[[35 40 65]
 [60 75 95]]
[[ 5 20 15]
 [20 25 25]]


Apply statistical operations like mean, median, std, min, and max
to analyze 2D array data.

In [ ]:
import numpy as np
scores = np.random.randint(0, 101, (4, 4))
print("Test Scores (4x4):\n", scores)
row_mean = np.mean(scores, axis=1)
print("\nRow-wise Mean (per student):\n", row_mean)
col_mean = np.mean(scores, axis=0)
print("\nColumn-wise Mean (per subject):\n", col_mean)
std_dev = np.std(scores)
variance = np.var(scores)
print("\nStandard Deviation of all scores:", std_dev)
print("Variance of all scores:", variance)
max_value = np.max(scores)
min_value = np.min(scores)
max_index = np.unravel_index(np.argmax(scores), scores.shape)
min_index = np.unravel_index(np.argmin(scores), scores.shape)
print("\nMaximum Score:", max_value)
print("Minimum Score:", min_value)

Test Scores (4x4):
 [[ 5 90 18 18]
 [30 56 19 84]
 [89 93 21 36]
 [90 37  6 58]]

Row-wise Mean (per student):
 [32.75 47.25 59.75 47.75]

Column-wise Mean (per subject):
 [53.5 69.  16.  49. ]

Standard Deviation of all scores: 31.864704219559297
Variance of all scores: 1015.359375

Maximum Score: 93
Minimum Score: 5


Apply statistical operations like mean, median, std, min, and max
to analyze 2D array data

In [ ]:
import numpy as np
image = np.random.randint(0, 256, (3, 3, 3))
print("Original Image:\n", image)
red   = image[:, :, 0]
green = image[:, :, 1]
blue  = image[:, :, 2]
print("\nRed Channel:\n", red)
print("\nGreen Channel:\n", green)
print("\nBlue Channel:\n", blue)
print("\nAverage Red:", np.mean(red))
print("Average Green:", np.mean(green))
print("Average Blue:", np.mean(blue))
bright = np.clip(np.add(image, 50), 0, 255)
print("\nBrightened Image:\n", bright)
dark = np.clip(np.subtract(image, 50), 0, 255)
print("\nDarkened Image:\n", dark)


Original Image:
 [[[210  80 230]
  [164  71  71]
  [164 129 108]]

 [[148 134 151]
  [ 81  95 115]
  [ 33 133  31]]

 [[171 221  78]
  [ 63  44  65]
  [ 36 132  24]]]

Red Channel:
 [[210 164 164]
 [148  81  33]
 [171  63  36]]

Green Channel:
 [[ 80  71 129]
 [134  95 133]
 [221  44 132]]

Blue Channel:
 [[230  71 108]
 [151 115  31]
 [ 78  65  24]]

Average Red: 118.88888888888889
Average Green: 115.44444444444444
Average Blue: 97.0

Brightened Image:
 [[[255 130 255]
  [214 121 121]
  [214 179 158]]

 [[198 184 201]
  [131 145 165]
  [ 83 183  81]]

 [[221 255 128]
  [113  94 115]
  [ 86 182  74]]]

Darkened Image:
 [[[160  30 180]
  [114  21  21]
  [114  79  58]]

 [[ 98  84 101]
  [ 31  45  65]
  [  0  83   0]]

 [[121 171  28]
  [ 13   0  15]
  [  0  82   0]]]
