<a href="https://colab.research.google.com/github/2303a51295madhuri/python-for-data-science/blob/main/lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Perform basic arithmetic operations like addition and subtraction
on 2D NumPy arrays representing matrices

In [ ]:
import numpy as np
A=np.array([[20,30,40],[40,50,60]])
B=np.array([[15,10,25],[20,25,35]])
print(A)
print(B)


[[20 30 40]
 [40 50 60]]
[[15 10 25]
 [20 25 35]]


In [ ]:
addition=np.add(A,B)
print(addition)
subtraction=np.subtract(A,B)
print(subtraction)

[[35 40 65]
 [60 75 95]]
[[ 5 20 15]
 [20 25 25]]


Apply statistical operations like mean, median, std, min, and max
to analyze 2D array data.

In [ ]:
import numpy as np
scores = np.random.randint(0, 101, (4, 4))
print("Test Scores (4x4):\n", scores)
row_mean = np.mean(scores, axis=1)
print("\nRow-wise Mean (per student):\n", row_mean)
col_mean = np.mean(scores, axis=0)
print("\nColumn-wise Mean (per subject):\n", col_mean)
std_dev = np.std(scores)
variance = np.var(scores)
print("\nStandard Deviation of all scores:", std_dev)
print("Variance of all scores:", variance)
max_value = np.max(scores)
min_value = np.min(scores)
max_index = np.unravel_index(np.argmax(scores), scores.shape)
min_index = np.unravel_index(np.argmin(scores), scores.shape)
print("\nMaximum Score:", max_value)
print("Minimum Score:", min_value)

Test Scores (4x4):
 [[ 55  66  93  66]
 [ 40  96  89  26]
 [ 17  46   2  98]
 [ 67  54  49 100]]

Row-wise Mean (per student):
 [70.   62.75 40.75 67.5 ]

Column-wise Mean (per subject):
 [44.75 65.5  58.25 72.5 ]

Standard Deviation of all scores: 29.0871535217869
Variance of all scores: 846.0625

Maximum Score: 100
Minimum Score: 2


Apply statistical operations like mean, median, std, min, and max
to analyze 2D array data

In [ ]:
import numpy as np
image = np.random.randint(0, 256, (3, 3, 3))
print("Original Image:\n", image)
red   = image[:, :, 0]
green = image[:, :, 1]
blue  = image[:, :, 2]
print("\nRed Channel:\n", red)
print("\nGreen Channel:\n", green)
print("\nBlue Channel:\n", blue)
print("\nAverage Red:", np.mean(red))
print("Average Green:", np.mean(green))
print("Average Blue:", np.mean(blue))
bright = np.clip(np.add(image, 50), 0, 255)
print("\nBrightened Image:\n", bright)
dark = np.clip(np.subtract(image, 50), 0, 255)
print("\nDarkened Image:\n", dark)


Original Image:
 [[[198 131 126]
  [ 58  61 143]
  [ 87 100 226]]

 [[186 250 144]
  [247  11  47]
  [ 60 112  11]]

 [[218  84  42]
  [196 249  52]
  [ 92  55 208]]]

Red Channel:
 [[198  58  87]
 [186 247  60]
 [218 196  92]]

Green Channel:
 [[131  61 100]
 [250  11 112]
 [ 84 249  55]]

Blue Channel:
 [[126 143 226]
 [144  47  11]
 [ 42  52 208]]

Average Red: 149.11111111111111
Average Green: 117.0
Average Blue: 111.0

Brightened Image:
 [[[248 181 176]
  [108 111 193]
  [137 150 255]]

 [[236 255 194]
  [255  61  97]
  [110 162  61]]

 [[255 134  92]
  [246 255 102]
  [142 105 255]]]

Darkened Image:
 [[[148  81  76]
  [  8  11  93]
  [ 37  50 176]]

 [[136 200  94]
  [197   0   0]
  [ 10  62   0]]

 [[168  34   0]
  [146 199   2]
  [ 42   5 158]]]
